### ISSUE TITLE
Homepage - Intro section

### ISSUE THREAD

**Issue by Sean-opx** [ResetNetwork/apply-app#26]
**Describe the bug**
– Scroll jacking – A small/medium scroll from the initial screen seems to easily confuse the scroll jacking and can result in it locking to a half way position (shown below)

**Expected behavior**
https://www.wolffolins.com/

**Screenshots**
<img width="1532" alt="Screenshot 2020-03-02 at 11 42 12" src="https://user-images.githubusercontent.com/61156618/75687787-3c9d1a00-5c96-11ea-8894-b80f92075dd8.png">

**Comment by scott-psycle** [comment]
@Sean-opx I'm unable to recreate this issue.  Could you confirm which browser you're using please?

There's also an ongoing discussion about ditching the scroll jacking.

**Comment by Sean-opx** [comment]
Hi Scott

We were seeing the issue on a MacBook Pro (15-inch, 2017) on Chrome. Keep us posted.

Thanks,

**Comment by scott-psycle** [comment]
@Sean-opx I've managed to replicate the behaviour.  We've had to implement a few rules to determine when and which way to scroll.  The rules are:

1. IF LESS THAN HALF A SECTION SCROLLED
- user has scrolled a fair way into a section (don't hi-jack scrolling as they're not near another section and are currently scrolling through a section - amount scrolled has to be at least half the window height)
- user is fairly close to section top so let's scroll to it
2. IF OVER HALF A SECTION IS SCROLLED
- if some of the section's content is below the fold then don't scroll to the next section (otherwise there's content they can never read)
- otherwise scroll to next section

Unfortunately it's not possible to replicate the Wolf Olins behaviour as the sections of the Reset site don't fit to the window as the browser is resized.

**Comment by Sean-opx** [comment]
Hi Scott

Given that we are planning to reduce the spacing between the modules on the
homepage, we're wondering if it would be more user friendly to remove the
scroll jacking altogether as there will be less differentiation between
each of the sections. Looping in Sian to get her view on this. @Sian Aherne
<saherne@luminategroup.com> are you happy for us to remove the scroll
jacking on the homepage to make room for the reduced module spacing?

Thanks,
---


*Sean Croucher**Project Manager*

–
*OPX*

The Timber Yard, 53 Drysdale Street, London N1 6ND
Registered Office. OPX Ltd, Company no 06289138, Registered in England, VAT
no 657 5539 94.

T: +44 (0)20 7729 6295
opx.studio
Follow us on Instagram <https://www.instagram.com/opx.studio>, Medium
<https://medium.com/@OPX_London>, and Tumblr <https://opxstudio.tumblr.com/>

**Comment by Sean-opx** [comment]
Hey - yes, we’re happy to remove the scroll jacking

Thanks!
Sian

**Comment by scott-psycle** [comment]
Ok, we'll take it out.

**Comment by scott-psycle** [comment]
@Sean-opx The scroll jacking has been removed.
