### ISSUE TITLE
Labels/questions text applications is wrapping to narrowly 

### ISSUE THREAD

**Issue by danblah** [ResetNetwork/apply-app#54]
see https://test-apply.reset.tech/digital-future-fund/, "Please provide any other relevant information about the structure or formation of the company." for example.

**Comment by frjo** [comment]
That is part of the new styling for reset. I believe they envisioned that there would always be a help link. Since that is not the case it looks bad in many cases.

![Skärmavbild 2020-03-16 kl  08 29 30](https://user-images.githubusercontent.com/191392/76733041-5479a100-6760-11ea-94ae-49e4dba1a43d.png)

**Comment by scott-psycle** [comment]
@danblah Fredrik is correct that 50% of the width is reserved for the help label.  The simplest solution to this will be to move the help label below the field title and help text.

If you're ok with that we'll get it updated.  Let me know if you want to go ahead with the change.
