### ISSUE TITLE
Fix this broken stuff identified after the close of this last round

### ISSUE THREAD

**Issue by danblah** [ResetNetwork/apply-app#89]
1. How do I change the workflow for all the applications in a closed round from "Concept note & proposal" to "Request with external review"? This is for ICFellow-20200501, ROFFund-20200501, and RFellow-20200501.
2. ~~Rename the slug on this page to https://www.reset.tech/open-calls/future-fund/ https://www.reset.tech/open-calls/reset-our-future-fund/ and fix whatever other page is blocking it.~~ 
3. ~~Rename the slug for https://apply.reset.tech/reset-our-future-fund-new/ to be https://apply.reset.tech/reset-our-future-fund/.~~
4. ~~Fix the Cloudflare unable-to-purge-cache error~~
5. ~~Fix the duplicate slack msg for each notification in #notify~~
6. Enhance/fix the fund editing pages to disallow changing the workflow or a fund with existing rounds (which seems to really break things).
7. Fix all those 500 errors on saving any changes (like the slug, workflow, title, etc) to a fund page and add any logic checks to keep editing from even happening if it is going to break things.
8. Come up with some solution to allowing a fund's workflow and other settings to be changed, even if there are existing rounds, so that future rounds use the new properties, and we don't have to create multiple funds for the same actual fund (which requires a lot of manual enabling/renaming/disabling for round rollovers which result in failed application submissions)
9. Come up with a recommended solution for "opening" up a round that just closed so that a failed submission can be included in the round, submitted by either the applicant or a mgr. When the following round automatically opens for the same fund after, there's no apparent way to do allow an application into the old round for the same fund :-/
10. ~~Allow the deletion of unused application forms. All the round creation and deletion creates all these superfluous application form copies that need to be deleted.~~
11. Why have a delete or edit option for Funds when neither actual work and create 500 errors?
12. ~~Make individual tickets for all of the above as needed.~~

**Comment by frjo** [comment]
1. This has to be done in the database directly. List the affected round(s) and I'll fix it.
2. Done. Did you have an issue doing this? Seems to just work, the Cloudflare cache might confuse things however.
3. Done.
4. https://github.com/OpenTechFund/hypha/issues/1969
5. All notifications goes to the default channel (set to #notify now for Reset). You can then add additional channels for each fund. Reset has added "#notify" so it becomes double. I think the default part should be removed forcing staff to always explicitly add a channel for each fund. This would be a more generic solution than the current one. If OTF really needs the notifications to go to both a default channel and a custom channel we could allow a comma separated list of channels.
6. Must do some testing here but changing stuff on a fund should work since all the info is copied to the round making the round stand alone so to speak. The next round you create will get the new values. The old ones should be unaffected.
7. Will test.
8. This is how I thought it worked now, will test for bugs.
9. Issue https://github.com/OpenTechFund/hypha/issues/1970
10. PR https://github.com/OpenTechFund/hypha/pull/1968
11. The delete button should not show when there are rounds, issue https://github.com/OpenTechFund/hypha/issues/1971
12. Done.

**Comment by danblah** [comment]
@frjo

1. ICFellow-20200501, ROFFund-20200501, and RFellow-20200501.
2. Thanks. Yes, couldn't do it. If I remember right, I'd get the 500 error.
3. Same.
4. Thanks.
5. Can you make a ticket for this in the main repo? And or also, could we check for dups as well? So we're clear, just remove the #notify from each fund?
6. This def needs testing. I was getting all kinds of weird behaviour... slugs, titles, fields not saving.
7. Same.
8. Def doesn't work this way.
9. Thanks.
10. Thanks.
11. Thanks.
12. Big thanks!

**Comment by frjo** [comment]
@danblah I have fixed the rounds in 1. now.

**Comment by frjo** [comment]
@danblah 5. Yes, just remove the Slack channel "notify" from the funds. Added issue to Hypha repo.

**Comment by frjo** [comment]
@danblah 6. I have now tested and editing funds have no effect at all on existing rounds from what I can tell. The DB entry for the round is not touched at all, just as it should be.

**Comment by frjo** [comment]
@danblah Tested Wagtail admin with my iPhone and it seems to work ok. Found no real issues. Apart from that it is a horrendous experience editing text in a mobil browser.

**Comment by frjo** [comment]
@danblah The issue I can replicate is assigned reviewers etc. on submissions, that is a known bug in Hypha and/or the "select2" package. https://github.com/OpenTechFund/hypha/issues/1758
